### ISSUE TITLE
Needs a screenshot

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.gnome.Fractal#2] opened 2017-12-25 12:47 UTC
This app needs one or more screenshots added to the appdata, otherwise it looks a bit rubbish in software stores.

**Comment by danigm** [comment] 2017-12-25 17:09
There are screenshots in the appdata, but maybe the appdata isn't correct:

https://gitlab.gnome.org/danigm/fractal/blob/master/fractal-gtk/res/org.gnome.Fractal.appdata.xml

**Comment by Alexander-Wilms** [comment] 2018-04-07 10:36
The screenshot shows up now, but the description is missing: https://flathub.org/apps/details/org.gnome.Fractal

**Comment by danigm** [comment] 2018-04-07 10:50
The description is in the appdata: https://gitlab.gnome.org/World/fractal/blob/master/fractal-gtk/res/org.gnome.Fractal.appdata.xml#L10-12

I don't know if there's a problem with that description or if it's a bug in the flathub page.

**Comment by barthalion** [comment] 2018-04-08 18:00
The problem is with the appdata. You need to put the content of the `<description>` between `<p>` tags.

**Comment by danigm** [comment] 2018-04-08 18:07
Thanks, the description should appear in the next release, I'll close this issue.

**Closed by danigm** 2018-04-08 18:07 UTC
