### ISSUE TITLE
Fails to launch on ARM

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.gnome.Fractal#3] opened 2018-02-13 18:25 UTC
"GLib:ERROR:gvariant-serialiser.c:167:g_variant_serialised_check: assertion failed (alignment & (gsize) serialised.data == 0): (4 == 0)"

**Comment by pwithnall** [comment] 2018-02-14 09:20
Would you be able to get a backtrace?

**Comment by nedrichards** [comment] 2018-02-14 11:50
Reported upstream at https://gitlab.gnome.org/danigm/fractal/issues/88

@pwithnall I don't have an ARM device with me currently - @rshuler may be able to help.

**Comment by danigm** [comment] 2018-02-14 11:51
I'm trying to fix this with flatpak run --arch=arm, but it takes a lot of time to build, I'm on it.

**Comment by danigm** [comment] 2018-02-14 18:32
It doesn't work, I tried to compile to arm, but the build never ends... I've also ask in the gnome #rust channel to the gtk-rs people and slomo points me to this patch: https://github.com/gtk-rs/gio/commit/0ee69c67fbf8848787b77a91df94113c7692ec10

Then suggested to use Bytes::from instead of Bytes::from_static. I've made that change and maybe that fixes the problem.

I'll try with the next version 0.1.14. If this doesn't fix the problem I'll need to find a way to compile for arm

**Comment by rshuler** [comment] 2018-02-14 19:15
@pwithnall: Here's a backtrace.  Let me know if you need any further information from this system.

```
endless@endless:~$ flatpak run --allow=devel -d --command=bash org.gnome.Fractal
bash-4.3$ gdb fractal
GNU gdb (GDB) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-unknown-linux-gnueabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from fractal...(no debugging symbols found)...done.
(gdb) r
Starting program: /app/bin/fractal 
warning: File "/usr/lib/libthread_db-1.0.so" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /usr/lib/libthread_db-1.0.so
line to your configuration file "/sysroot/home/endless/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/sysroot/home/endless/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.

Program received signal SIGILL, Illegal instruction.
0xb615e188 in ?? () from /lib/libcrypto.so.1.0.2
(gdb) bt
Python Exception <class 'SystemError'> <built-in function isinstance> returned a result with an error set: 
Python Exception <class 'SystemError'> <built-in function isinstance> returned a result with an error set: 
Python Exception <class 'SystemError'> <built-in function isinstance> returned a result with an error set: 
#0  0xffffffff in #1  0xffffffff in #2  0xffffffff in (gdb) 
```

**Comment by pwithnall** [comment] 2018-02-22 12:48
That backtrace contains no useful information (the stack seems corrupt), but given the analysis done in https://bugzilla.gnome.org/show_bug.cgi?id=793394, I’m fairly confident about the causes of the problem here, and how to fix it. Someone just needs to find time to do the fix.

**Comment by nedrichards** [comment] 2018-02-22 14:46
This should have been fixed by https://gitlab.gnome.org/danigm/fractal/commit/36a6f19ee4d70349bfa8cffd875d95eafbba2be3 which has been released to flathub already. @rshuler is this fixed?

**Comment by rshuler** [comment] 2018-02-26 19:18
Yes, this is now fixed on ARM.  I don't have a Riot.im account to actually exercise the app's functionality, but the UI launches fine and the "Create Account" button launches the registration page in the browser.

**Closed** 2018-05-25 18:37 UTC
